import {strict as assert} from 'node:assert';
import {initialState,demoScenario,reduceDemo,validation,consultationReasons,subtotal,pilotSlots,canPay,products,referenceFee} from '../lib/demo.ts';
const act=reduceDemo;
const ready=id=>act(demoScenario(id),{type:'edit',patch:{handoff:true}});
function payment(s,method='card'){s=act(s,{type:'select_payment',method});s=act(s,{type:'start_payment',attemptId:'a'});assert.equal(act(s,{type:'start_payment',attemptId:'b'}),s);return act(s,{type:'finish_payment',attemptId:'a',revision:s.revision,success:true});}
for(const id of [1,2,3]){let s=ready(id);assert.deepEqual(validation(s.draft),[]);s=act(s,{type:'submit'});assert.equal(s.status,'review');assert.equal(canPay(s),false);s=act(s,{type:'approve'});assert.equal(s.status,'payment');s=payment(s);assert.equal(s.status,'confirmed');assert.equal(canPay(s),false);assert.equal(payment(s),s);}
let approved=act(ready(4),{type:'submit'});assert.equal(canPay(approved),false);approved=act(approved,{type:'quote',fee:2000,note:'確認条件'});assert.equal(approved.status,'quoted');assert.equal(approved.quote.total,4400);assert.equal(canPay(approved),false);approved=act(approved,{type:'accept'});assert.equal(payment(approved,'paypay').status,'confirmed');
let declined=act(act(ready(5),{type:'submit'}),{type:'decline',reason:'配送枠不足'});assert.equal(declined.status,'declined');assert.equal(canPay(declined),false);for(const mode of ['takeout','date','place']){const alt=act(declined,{type:'alternative',mode});assert.equal(alt.status,'draft');assert.equal(alt.quote,null);assert.equal(alt.draft.handoff,false);assert.equal(canPay(alt),false);}
let bbq=ready(6);assert.equal(subtotal(bbq.draft),16800);bbq=act(bbq,{type:'submit'});assert.equal(bbq.status,'review');assert.equal(act(bbq,{type:'approve'}),bbq);bbq=act(bbq,{type:'quote',fee:800,note:'本人受渡し'});assert.equal(canPay(bbq),false);assert.equal(payment(act(bbq,{type:'accept'})).status,'confirmed');
for(const field of [{cart:{bowl:3}},{date:'2028-01-01'},{destId:'demo-sweetgrass'},{people:7},{time:'18:00–18:30'}]){const stale=act(approved,{type:'edit',patch:field});assert.equal(stale.quote,null);assert.equal(stale.payment.method,'');assert.equal(canPay(stale),false);}
for(const patch of [{kitchen:false},{driver:false},{productReady:false},{special:true},{cart:{bowl:8}}]){const s=act(ready(1),{type:'edit',patch});assert.ok(consultationReasons(s.draft).length);assert.equal(act(act(s,{type:'submit'}),{type:'approve'}).status,'review');}
for(const id of pilotSlots){const s=act(ready(1),{type:'edit',patch:{destId:id}});assert.deepEqual(validation(s.draft),[]);assert.ok(consultationReasons(s.draft).length);assert.equal(act(act(s,{type:'submit'}),{type:'approve'}).status,'review');}
let q=act(ready(1),{type:'submit'});q=act(q,{type:'ask',question:'何時に到着できますか？'});assert.equal(q.status,'awaiting_answer');assert.equal(canPay(q),false);q=act(q,{type:'answer',answer:'17時です'});assert.equal(q.status,'review');q=act(q,{type:'approve'});q=act(q,{type:'select_payment',method:'apple_pay'});q=act(q,{type:'start_payment',attemptId:'failed'});q=act(q,{type:'finish_payment',attemptId:'failed',revision:q.revision,success:false});assert.equal(q.status,'payment');assert.equal(q.payment.phase,'failed');q=payment(q,'google_pay');assert.equal(q.status,'confirmed');
let inflight=act(approved,{type:'select_payment',method:'card'});inflight=act(inflight,{type:'start_payment',attemptId:'late'});const cleared=act(inflight,{type:'reset'});assert.deepEqual(cleared,initialState());assert.equal(act(cleared,{type:'finish_payment',attemptId:'late',revision:inflight.revision,success:true}),cleared);
assert.ok(validation({...ready(1).draft,cart:{soup:1}}).length);assert.ok(validation({...ready(6).draft,people:0}).length);assert.equal(act(initialState(),{type:'submit'}).status,'draft');
console.log('PASS: Six order paths; all 12 provisional facilities; all payment candidates; failure/retry; duplicate and stale completion guards; quote invalidation; additional questions; decline alternatives; complete reset; channel/input gates.');

assert.equal(referenceFee(ready(1).draft),1000);assert.equal(referenceFee(ready(4).draft),2000);assert.equal(referenceFee(ready(6).draft),0);assert.equal(products.filter(p=>p.groupId).length,40);
