"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,ShoppingBag,Utensils,Flame,Plus,Minus,Clock3,Coffee,Info,CheckCircle2,MapPin,Truck,WifiOff,MessageCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {initialState,reduceDemo,products,bbqSets,pilotDestinations,subtotal,validation,consultationReasons,referenceFee,statusLabels,canPay,MINIMUM_ORDER_AMOUNT,minimumOrderShortfall,type Draft,type Action,type DemoState} from '@/lib/demo';
import {PREVIEW_MODE,clearPreviewStorage,type PreviewScreen,type Section} from '@/lib/preview';
import {Brand,BrandIntro} from '@/components/food/intro';
import {Choice,Tick,Notice,Totals,OrderLines,OrderDetail,Schedule,DestinationPicker,yen} from '@/components/food/order-parts';
import {PaymentPanel,methods} from '@/components/food/payment-panel';
import {StorePanel} from '@/components/food/store-panel';
import {useConnectivity,PwaUpdate} from '@/components/food/pwa';
const navigation=[{id:'menu',label:'メニュー',icon:Utensils},{id:'bbq',label:'BBQ予約',icon:Flame},{id:'cart',label:'カート',icon:ShoppingBag},{id:'status',label:'注文状況',icon:Clock3},{id:'guide',label:'ご利用案内',icon:Info}] as const;
export default function Home(){
 const [state,setState]=useState<DemoState>(initialState),stateRef=useRef(state);
 const [screen,setScreen]=useState<PreviewScreen>('intro'),[section,setSection]=useState<Section>('menu');
 const [filter,setFilter]=useState('all'),[category,setCategory]=useState('all'),[answer,setAnswer]=useState(''),[submitted,setSubmitted]=useState(false),[seatInfo,setSeatInfo]=useState(false),[unread,setUnread]=useState(false);
 const online=useConnectivity();const paymentTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const paymentLock=useRef(false);const paymentSequence=useRef(0);const epoch=useRef(0);
 const previewBar=useRef<HTMLDivElement>(null),bottomBar=useRef<HTMLElement>(null);
 const finishIntro=useCallback(()=>{setScreen('customer');setSection('menu');},[]);
 function send(a:Action){const next=reduceDemo(stateRef.current,a);stateRef.current=next;setState(next);return next;}
 function edit(p:Partial<Draft>){if(paymentTimer.current)clearTimeout(paymentTimer.current);paymentLock.current=false;send({type:'edit',patch:p});setSubmitted(false);}
 function go(s:Section){setSection(s);if(s==='status')setUnread(false);window.history.pushState({food:true,epoch:epoch.current,section:s},'');window.scrollTo({top:0,behavior:'instant'});}
 function switchScreen(s:PreviewScreen){setScreen(s);window.scrollTo({top:0,behavior:'instant'});}
 function reset(){epoch.current++;if(paymentTimer.current)clearTimeout(paymentTimer.current);paymentLock.current=false;clearPreviewStorage();send({type:'reset'});setSection('menu');setScreen('intro');setFilter('all');setCategory('all');setAnswer('');setSubmitted(false);setSeatInfo(false);setUnread(false);window.history.replaceState({food:true,epoch:epoch.current,section:'menu'},'');window.scrollTo({top:0,behavior:'instant'});}
 useEffect(()=>{window.history.replaceState({food:true,epoch:epoch.current,section:'menu'},'');const pop=(e:PopStateEvent)=>{if(e.state?.food&&e.state.epoch===epoch.current&&navigation.some(n=>n.id===e.state.section)){setSection(e.state.section);setScreen(old=>old==='customer'?'customer':old);}else{setSection('menu');}window.scrollTo({top:0,behavior:'instant'});};window.addEventListener('popstate',pop);return ()=>{window.removeEventListener('popstate',pop);if(paymentTimer.current)clearTimeout(paymentTimer.current);};},[]);
 useEffect(()=>{const el=previewBar.current;if(!el)return;const obs=new ResizeObserver(()=>document.documentElement.style.setProperty('--preview-height',`${el.getBoundingClientRect().height}px`));obs.observe(el);return ()=>obs.disconnect();},[]);
 useEffect(()=>{const el=bottomBar.current;if(!el)return;const obs=new ResizeObserver(()=>document.documentElement.style.setProperty('--nav-height',`${el.getBoundingClientRect().height}px`));obs.observe(el);return ()=>obs.disconnect();},[screen]);
 const d=state.draft,qty=Object.values(d.cart).reduce((a,b)=>a+b,0),sub=subtotal(d),fee=referenceFee(d),errors=validation(d),busy=state.payment.phase==='processing';
 const changeQty=(id:string,delta:number)=>{const p=products.find(p=>p.id===id);const cart={...stateRef.current.draft.cart,[id]:Math.max(0,Math.min(30,(stateRef.current.draft.cart[id]??0)+delta))};edit({kind:'meal',cart,...(p?.channel==='takeout'?{fulfillment:'takeout' as const}:p?.channel==='delivery'?{fulfillment:'delivery' as const}:{})});};
 function submit(){setSubmitted(true);if(!online)return;const next=send({type:'submit'});if(next.status==='review'){setUnread(true);switchScreen(PREVIEW_MODE?'toStore':'customer');setSection('status');}}
 function shopAction(a:Action){if(!online||!PREVIEW_MODE)return;const next=send(a);if(next.status!=='review'){setUnread(true);switchScreen('toCustomer');}}
 function pay(){if(!online||paymentLock.current||!canPay(stateRef.current)||!stateRef.current.payment.method)return;paymentLock.current=true;const id=`${epoch.current}-${++paymentSequence.current}`,revision=stateRef.current.revision;const next=send({type:'start_payment',attemptId:id});if(next.payment.attemptId!==id){paymentLock.current=false;return;}paymentTimer.current=setTimeout(()=>{send({type:'finish_payment',attemptId:id,revision,success:navigator.onLine});paymentLock.current=false;},1400);}
 function alternative(mode:'takeout'|'date'|'place'){send({type:'alternative',mode});setSubmitted(false);go(stateRef.current.draft.kind==='bbq'?'bbq':'cart');}
 const totals=<Totals sub={state.quote?.subtotal??sub} fee={state.quote?.fee??fee} total={state.quote?.total??sub+fee} title={state.quote?'店舗からの見積':'参考見積'}/>;
 const endButton=<Button variant="outline" className="wide end-button" onClick={reset}>確認を終えてトップへ</Button>;
 const contact=<><section className="form-section"><h2>ご連絡先</h2><div className="two-fields"><div className="field"><label htmlFor="contact-name">お名前</label><Input id="contact-name" autoComplete="off" value={d.contactName} maxLength={80} onChange={e=>edit({contactName:e.target.value})}/></div><div className="field"><label htmlFor="contact-phone">電話番号</label><Input id="contact-phone" type="tel" inputMode="tel" autoComplete="off" value={d.contactPhone} maxLength={16} onChange={e=>edit({contactPhone:e.target.value})}/></div></div><div className="field"><label htmlFor="order-note">ご要望・補足（任意）</label><Textarea id="order-note" value={d.note} maxLength={500} onChange={e=>edit({note:e.target.value,special:!!e.target.value.trim()})}/></div></section><Tick checked={d.handoff} onChange={handoff=>edit({handoff})}>施設スタッフに預けず、注文者本人が直接受け取ります。</Tick></>;
 const submitBox=<><Notice>{d.fulfillment==='delivery'?<>デリバリーの最低注文金額は商品代金{yen(MINIMUM_ORDER_AMOUNT)}です（配達料を除く）。{minimumOrderShortfall(d)>0&&<p role="status">あと{yen(minimumOrderShortfall(d))}分の商品を追加してください。</p>}</>:<>テイクアウトは最低注文金額なしでご利用いただけます。</>}</Notice>{submitted&&errors.length>0&&<div className="validation-hint" role="alert"><b>入力内容をご確認ください</b><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}<Notice>まず店舗が商品・日時・受渡し条件を確認します。この時点では注文確定・お支払いは行いません。</Notice><Button className="wide" disabled={!online||state.status!=='draft'||minimumOrderShortfall(d)>0} onClick={submit}>{consultationReasons(d).length?'内容を確認して相談する':'注文内容を確認して申し込む'}<ArrowRight size={18}/></Button></>;
 return <div className="food-app"><div ref={previewBar} className="preview-bar"><b>OWNER PREVIEW v2.1</b><span>商品・価格は仮設定／実際の注文・決済は行われません</span></div>
 {screen==='intro'?<BrandIntro onFinish={finishIntro}/>:<><header className="site-header"><button onClick={()=>{if(screen==='customer')go('menu');}} aria-label="SHINING food メニューへ"><Brand/></button><span className="header-caption">北軽井沢・嬬恋の滞在に、<br/>気になるおいしさを。</span>{screen==='customer'&&<button className="header-order" onClick={()=>go(state.status==='draft'?'cart':'status')}><ShoppingBag size={21}/><span>{state.status==='draft'?'カート':'注文状況'}</span><b>{d.kind==='bbq'?1:qty}</b></button>}</header>
 {!online&&<div className="offline-alert" role="alert"><WifiOff size={19}/>通信が切れています。内容はこの画面に保持しています。接続後に操作を続けてください。</div>}
 {screen==='toStore'||screen==='toCustomer'?<main className="transition-screen"><span className="eyebrow">{screen==='toStore'?'REQUEST RECEIVED':'RESPONSE READY'}</span><h1>{screen==='toStore'?'お申込みを受け付けました':'店舗からの回答を確認します'}</h1><p>{screen==='toStore'?'続いて、店舗側の受付・確認画面へ進みます。':'回答内容をお客様側の画面で確認します。'}</p><Button className="wide" onClick={()=>{if(screen==='toStore')switchScreen('store');else{switchScreen('customer');setSection('status');setUnread(false);}}}>{screen==='toStore'?'店舗側の確認へ進む':'お客様の画面へ戻る'}<ArrowRight size={18}/></Button><Button variant="ghost" onClick={()=>{if(screen==='toStore'){switchScreen('customer');setSection('status');}else switchScreen('store');}}><ArrowLeft size={17}/>前の画面に戻る</Button></main>:
 screen==='store'&&PREVIEW_MODE?<StorePanel state={state} onAction={shopAction} onReviewResult={()=>switchScreen('toCustomer')} online={online}/>:
 <main className="shell" id="main-content">
 {state.notice&&section!=='menu'&&<div className="live-notice" role="status">{state.notice}</div>}
 {section==='menu'&&<><div className="menu-heading"><div><p className="eyebrow">GOOD FOOD. GOOD STAY.</p><h1>今日は、どこで食べよう。</h1><p>滞在先へお届け。お出かけ前にテイクアウト。</p><p className="subtle">デリバリーは商品代金{yen(MINIMUM_ORDER_AMOUNT)}から（配達料別）。テイクアウトは最低注文金額なし。</p></div><button className="text-link" onClick={()=>go('guide')}>はじめての方へ<ArrowRight size={17}/></button></div><div className="filter-row" aria-label="商品を絞り込む">{[['all','すべて'],['delivery','デリバリー'],['takeout','テイクアウト'],['both','両対応']].map(([v,l])=><button key={v} aria-pressed={filter===v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{l}</button>)}</div><div className="catalog-tools"><Choice label="料理の種類" value={category} onChange={setCategory} items={[{value:'all',label:'すべての料理'},...Array.from(new Set(products.map(p=>p.category??'お食事'))).map(v=>({value:v,label:v}))]}/><p className="subtle">掲載候補の参考メニューです。提供方法・価格・内容を確認しています。</p></div><div className="product-grid">{products.filter(p=>category==='all'||(p.category??'お食事')===category).filter(p=>filter==='all'||(filter==='both'?p.channel==='both':p.channel==='both'||p.channel===filter)).map(p=><article className="product-card" key={p.id}><div className="product-image"><img src={p.image??'/images/rice-bowl.jpg'} alt={`${p.name} / ${p.imageLabel??'写真はイメージ'}`} loading="lazy"/><span>{p.imageLabel??'写真はイメージ'}</span></div><div className="product-body"><span className="pill">{p.channel==='both'?'デリバリー・テイクアウト':p.channel==='delivery'?'デリバリー候補':'テイクアウト候補'}</span><h2>{p.name}</h2><p>{p.description}</p><div className="price-row"><b>{yen(p.price)} <small>参考</small></b>{p.available===false?<span className="availability-note">提供再開を確認中</span>:(d.cart[p.id]??0)>0?<div className="quantity"><button aria-label={`${p.name}を減らす`} disabled={busy} onClick={()=>changeQty(p.id,-1)}><Minus size={17}/></button><output>{d.cart[p.id]}</output><button aria-label={`${p.name}を増やす`} disabled={busy} onClick={()=>changeQty(p.id,1)}><Plus size={17}/></button></div>:<Button size="sm" disabled={busy} onClick={()=>changeQty(p.id,1)} aria-label={`${p.name}を追加する`}><Plus size={17}/>追加する</Button>}</div></div></article>)}</div><button className="bbq-banner" onClick={()=>go('bbq')}><img src="/images/bbq-grill.jpg" alt="BBQのイメージ"/><div><p className="eyebrow">PLAN A LITTLE AHEAD</p><h2>集まる日のBBQを、事前に。</h2><p>人数と日時から、参考見積をつくれます。</p><span>BBQ予約へ <ArrowRight size={16}/></span></div></button><button className="asama-link" onClick={()=>go('asama')}><Coffee size={25}/><span><b>その場所で過ごす、おいしい時間。</b><small>Cafe&Barあさまについて</small></span><ArrowRight size={20}/></button></>}
 {section==='bbq'&&<><div className="bbq-intro"><img src="/images/bbq-grill.jpg" alt="BBQのイメージ写真"/><div><p className="eyebrow">BBQ / ADVANCE RESERVATION</p><h1>集まる日の食卓を、<br/>いっしょに準備。</h1><p>人数・日時・お届け先を選んで事前相談。<br/>店舗からの見積を確認してからお支払いへ。</p><small>写真はイメージ。食材・器材・サービス内容は確認中。</small></div></div>{d.kind!=='bbq'?<section className="panel start-bbq"><h2>BBQの予約相談をはじめる</h2><p>人数とセットから参考金額を確認できます。</p><Button disabled={busy} onClick={()=>edit({kind:'bbq',fulfillment:'delivery',people:6,setId:'standard'})}>人数・セットを選ぶ<ArrowRight size={18}/></Button></section>:state.status!=='draft'?<section className="panel"><h2>進行中のお申込みがあります</h2><Button onClick={()=>go('status')}>注文状況を見る</Button><Button variant="outline" disabled={busy} onClick={()=>edit({})}>条件を変更する</Button></section>:<div className="form-layout"><section className="panel"><h2>人数・セット</h2><div className="two-fields"><div className="field"><label htmlFor="bbq-people">人数（1〜30名）</label><Input id="bbq-people" type="number" min={1} max={30} value={d.people} onChange={e=>edit({people:Number(e.target.value)})}/></div><Choice label="BBQセット" value={d.setId} onChange={setId=>edit({setId})} items={bbqSets.map(x=>({value:x.id,label:`${x.name} / 1名 ${yen(x.price)}（参考）`}))}/></div><p className="subtle">{bbqSets.find(s=>s.id===d.setId)?.description}</p><Schedule d={d} edit={edit}/><DestinationPicker d={d} edit={edit}/>{contact}</section><aside className="panel summary">{totals}{submitBox}</aside></div>}</>}
 {section==='cart'&&(qty===0&&d.kind!=='bbq'?<section className="empty-state"><ShoppingBag size={42}/><h1>カートはまだ空です</h1><p>気になるひと皿を選んでください。</p><Button onClick={()=>go('menu')}>メニューを見る<ArrowRight size={18}/></Button></section>:state.status!=='draft'?<section className="panel narrow"><h1>お申込み内容</h1><OrderDetail state={state}/>{totals}<Button className="wide" onClick={()=>go('status')}>注文状況を確認する</Button>{!busy&&<Button variant="outline" className="wide" onClick={()=>{edit({});if(d.kind==='bbq')go('bbq');}}>条件を変更する</Button>}</section>:d.kind==='bbq'?<section className="panel narrow"><h1>BBQの予約内容</h1><OrderLines draft={d}/>{totals}<Button onClick={()=>go('bbq')}>日時・お届け先を入力する</Button></section>:<><div className="page-title"><p className="eyebrow">YOUR ORDER</p><h1>お受け取りの準備を。</h1><p>商品と日時、受取方法をご確認ください。</p></div><div className="form-layout"><section className="panel"><h2>選んだ商品</h2><div className="cart-edit">{products.filter(p=>(d.cart[p.id]??0)>0).map(p=><div key={p.id}><span>{p.name}<small>{yen(p.price)} / {p.channel==='both'?'両対応':p.channel==='delivery'?'デリバリー候補':'テイクアウト候補'}</small></span><div className="quantity"><button aria-label={`${p.name}を減らす`} onClick={()=>changeQty(p.id,-1)}><Minus size={17}/></button><output>{d.cart[p.id]}</output><button aria-label={`${p.name}を増やす`} onClick={()=>changeQty(p.id,1)}><Plus size={17}/></button></div></div>)}</div><Choice label="受取方法" value={d.fulfillment} onChange={v=>edit({fulfillment:v as Draft['fulfillment']})} items={[{value:'delivery',label:'デリバリー'},{value:'takeout',label:'テイクアウト'}]}/><Schedule d={d} edit={edit}/><DestinationPicker d={d} edit={edit}/>{contact}</section><aside className="panel summary">{totals}{submitBox}</aside></div></>)}
 {section==='status'&&(state.status==='draft'?<section className="empty-state"><Clock3 size={42}/><h1>お申込みはまだありません</h1><p>商品を選び、受取方法や日時をご指定ください。</p><Button onClick={()=>go(qty?'cart':'menu')}>{qty?'カートを確認する':'メニューを見る'}</Button></section>:<div className="form-layout"><section className="panel status-panel"><span className="status-icon">{state.status==='confirmed'?<CheckCircle2 size={29}/>:state.status==='awaiting_answer'?<MessageCircle size={29}/>:<Clock3 size={29}/>}</span><p className="eyebrow">ORDER STATUS</p><h1>{statusLabels[state.status]}</h1>
 {state.status==='review'&&<><p>商品・受渡し条件・厨房と配送の空きを確認しています。</p>{PREVIEW_MODE&&<Button className="wide" onClick={()=>switchScreen('toStore')}>受付内容の確認へ進む</Button>}</>}
 {state.status==='quoted'&&<><p>内訳と受取条件をお確かめください。了承後に支払方法をお選びいただけます。</p><div className="quote-message">{state.quote?.note}</div>{totals}<Button className="wide" disabled={!online} onClick={()=>send({type:'accept'})}>見積を了承して支払方法へ<ArrowRight size={18}/></Button></>}
 {canPay(state)&&<><div className="quote-message">{state.quote?.note}</div>{totals}<PaymentPanel state={state} select={method=>send({type:'select_payment',method})} onPay={pay} online={online}/></>}
 {state.status==='declined'&&<><p className="quote-message">{state.reason}</p><p>よろしければ、別の受取方法や日時をご相談ください。</p><div className="alternative-list"><Button variant="outline" onClick={()=>alternative('takeout')}>テイクアウトに変更する<ArrowRight size={17}/></Button><Button variant="outline" onClick={()=>alternative('date')}>別の日時を相談する<ArrowRight size={17}/></Button><Button variant="outline" onClick={()=>alternative('place')}>別の受取場所を選ぶ<ArrowRight size={17}/></Button></div>{endButton}</>}
 {state.status==='awaiting_answer'&&<><p className="quote-message">{state.question}</p><div className="field"><label htmlFor="customer-answer">店舗への回答</label><Textarea id="customer-answer" value={answer} maxLength={500} onChange={e=>setAnswer(e.target.value)}/></div><Button className="wide" disabled={!online||!answer.trim()} onClick={()=>{const next=send({type:'answer',answer});if(next.status==='review'){setAnswer('');switchScreen('toStore');}}}>回答して相談を続ける</Button>{endButton}</>}
 {state.status==='confirmed'&&<><p>お受け取りの日時と場所をご確認ください。当日は注文者ご本人がお越しください。</p>{totals}<p>お支払い方法：{methods.find(m=>m.id===state.payment.method)?.name}</p><OrderDetail state={state}/><button className="asama-link" onClick={()=>go('asama')}><Coffee/><span><b>Cafe&Barあさまで過ごす時間も。</b><small>お店と席予約のご案内</small></span><ArrowRight/></button>{endButton}</>}
 {!['confirmed','declined','review'].includes(state.status)&&!busy&&<Button variant="ghost" className="wide" onClick={()=>{edit({});go(d.kind==='bbq'?'bbq':'cart');}}>条件を変更して相談し直す</Button>}
 </section><aside className="panel summary"><h2>お申込みの内容</h2><OrderDetail state={state}/>{state.history.length>0&&<details className="history"><summary>これまでのやり取り</summary><ol>{state.history.map((h,i)=><li key={i}>{h}</li>)}</ol></details>}</aside></div>)}
 {section==='guide'&&<><div className="page-title"><p className="eyebrow">GOOD TO KNOW</p><h1>ご利用案内</h1></div><div className="guide-grid"><section className="panel"><Truck/><h2>お届けについて</h2><p>デリバリーの最低注文金額は商品代金{yen(MINIMUM_ORDER_AMOUNT)}です（配達料を除く・BBQの配達も対象）。テイクアウトは最低注文金額なしでご利用いただけます。</p><p>配達料は暫定で5kmまで1,000円、5km超は2,000円。商品代金10,000円以上で配達料無料です。距離・最終金額は店舗で確認します。</p><p>宿泊施設・キャンプ場、別荘地・管理センター、その他の住所へ。直線10kmを一次判定の目安とし、道路状況と受付枠を店舗で確認します。</p><p>範囲外・大口・BBQは事前相談。見積の了承後にお支払いへ進みます。</p></section><section className="panel"><MapPin/><h2>ご本人と、直接。</h2><p>施設スタッフへのお預けは行いません。施設内での受渡し許可と待ち合わせ場所を確認し、ご本人へお渡しします。</p><p>テイクアウトはCafe&Barあさまと共通の受取場所へ。住所・入口・対応時間は確認中です。</p></section><section className="panel"><Info/><h2>受付・お問い合わせ</h2><p>営業開始日、正式商品、販売価格、アレルゲン、受付時間は確認中です。個別の条件は、カートまたはBBQ予約からご相談いただけます。</p><p>問い合わせ先・LINE連携は準備中です。</p></section><section className="panel"><Coffee/><h2>Cafe&Barあさま</h2><p>厨房・受取場所を共有する、店内飲食の姉妹ブランド。自然とアートのそばで過ごす、一期一会の時間へ。</p><Button variant="outline" onClick={()=>go('asama')}>あさまと席予約のご案内<ArrowRight size={17}/></Button></section></div><section className="panel registry"><h2>施設候補一覧</h2><p>配達先の候補施設です。掲載は提携・配達許可を示すものではありません。施設への確認後に、配達可否と受渡し場所をご案内します。</p><div className="registry-grid">{pilotDestinations.map(f=><div key={f.id}><b>{f.name}</b><span>{f.type==='villa'?'別荘地・管理センター':'宿泊施設・キャンプ場'}</span><small>配達可否・受渡し条件は確認中</small></div>)}</div></section><section className="panel install-guide"><h2>ホーム画面から開く</h2><p>対応するブラウザーのメニューで「ホーム画面に追加」または「アプリをインストール」を選べます。通信がない時は接続案内を表示します。</p></section></>}
 {section==='asama'&&<section className="asama-card"><p className="eyebrow">OUR SISTER CAFE</p><Coffee size={38}/><h1>Cafe&Barあさま</h1><p>自然とアートのそばで、ひと息。<br/>その日、その場所の一期一会を。</p><p>SHINING foodと厨房・受取場所を共有しています。<br/>店内の料理・営業時間・席予約は準備中です。</p><Button onClick={()=>setSeatInfo(true)}>席予約について確認する<ArrowRight size={18}/></Button>{seatInfo&&<Notice>席予約の受付開始と窓口は確認中です。現在この画面からの予約・LINEへの送信は行っていません。</Notice>}<Button variant="outline" onClick={()=>go(state.status==='draft'?'menu':'status')}>{state.status==='draft'?'メニューへ戻る':'注文状況へ戻る'}</Button></section>}
 </main>}
 {screen==='customer'&&<nav ref={bottomBar} className="bottom-nav" aria-label="メインメニュー">{navigation.map(n=><button key={n.id} onClick={()=>go(n.id)} aria-current={section===n.id||(n.id==='guide'&&section==='asama')?'page':undefined}><span className="nav-icon"><n.icon size={22}/>{n.id==='cart'&&(qty>0||d.kind==='bbq')&&<b className="nav-badge">{d.kind==='bbq'?1:qty}</b>}{n.id==='status'&&unread&&<b className="nav-badge">!</b>}</span><span>{n.label}</span></button>)}</nav>}
 <PwaUpdate canUpdate={state.status==='draft'&&!qty&&d.kind!=='bbq'}/></>}
 </div>;
}
